# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BrakeChar.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(882, 743)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 20, 611, 711))
        self.label.setStyleSheet("image: url(:/newPrefix/wheelNum.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.comboBox_1 = QtWidgets.QComboBox(Dialog)
        self.comboBox_1.setGeometry(QtCore.QRect(220, 90, 73, 22))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 120, 73, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(570, 90, 73, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(Dialog)
        self.comboBox_4.setGeometry(QtCore.QRect(570, 120, 73, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(Dialog)
        self.comboBox_5.setGeometry(QtCore.QRect(220, 200, 73, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(Dialog)
        self.comboBox_6.setGeometry(QtCore.QRect(220, 230, 73, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_7 = QtWidgets.QComboBox(Dialog)
        self.comboBox_7.setGeometry(QtCore.QRect(570, 230, 73, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_8 = QtWidgets.QComboBox(Dialog)
        self.comboBox_8.setGeometry(QtCore.QRect(570, 200, 73, 22))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_9 = QtWidgets.QComboBox(Dialog)
        self.comboBox_9.setGeometry(QtCore.QRect(220, 340, 73, 22))
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_10 = QtWidgets.QComboBox(Dialog)
        self.comboBox_10.setGeometry(QtCore.QRect(220, 310, 73, 22))
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_11 = QtWidgets.QComboBox(Dialog)
        self.comboBox_11.setGeometry(QtCore.QRect(570, 310, 73, 22))
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_12 = QtWidgets.QComboBox(Dialog)
        self.comboBox_12.setGeometry(QtCore.QRect(570, 340, 73, 22))
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_13 = QtWidgets.QComboBox(Dialog)
        self.comboBox_13.setGeometry(QtCore.QRect(220, 420, 73, 22))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_14 = QtWidgets.QComboBox(Dialog)
        self.comboBox_14.setGeometry(QtCore.QRect(220, 450, 73, 22))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_15 = QtWidgets.QComboBox(Dialog)
        self.comboBox_15.setGeometry(QtCore.QRect(570, 420, 73, 22))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_16 = QtWidgets.QComboBox(Dialog)
        self.comboBox_16.setGeometry(QtCore.QRect(570, 450, 73, 22))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_17 = QtWidgets.QComboBox(Dialog)
        self.comboBox_17.setGeometry(QtCore.QRect(220, 530, 73, 22))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_18 = QtWidgets.QComboBox(Dialog)
        self.comboBox_18.setGeometry(QtCore.QRect(220, 560, 73, 22))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_19 = QtWidgets.QComboBox(Dialog)
        self.comboBox_19.setGeometry(QtCore.QRect(570, 560, 73, 22))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_20 = QtWidgets.QComboBox(Dialog)
        self.comboBox_20.setGeometry(QtCore.QRect(570, 530, 73, 22))
        self.comboBox_20.setObjectName("comboBox_20")
        self.checkBox_1 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_1.setGeometry(QtCore.QRect(300, 110, 81, 20))
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(540, 110, 81, 20))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(300, 220, 81, 20))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(540, 220, 81, 20))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(300, 330, 81, 20))
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(540, 330, 81, 20))
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(300, 440, 81, 20))
        self.checkBox_7.setText("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(540, 430, 81, 20))
        self.checkBox_8.setText("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(300, 550, 81, 20))
        self.checkBox_9.setText("")
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_10 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_10.setGeometry(QtCore.QRect(540, 550, 81, 20))
        self.checkBox_10.setText("")
        self.checkBox_10.setObjectName("checkBox_10")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 90, 121, 20))
        self.label_2.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(650, 90, 171, 20))
        self.label_3.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 120, 101, 20))
        self.label_4.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(650, 120, 171, 20))
        self.label_5.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(120, 200, 171, 20))
        self.label_6.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(120, 230, 171, 20))
        self.label_7.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(120, 310, 171, 20))
        self.label_8.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(120, 340, 171, 20))
        self.label_9.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(120, 450, 171, 20))
        self.label_10.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(120, 420, 171, 20))
        self.label_11.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(650, 200, 171, 20))
        self.label_12.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(650, 230, 171, 20))
        self.label_13.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(650, 340, 171, 20))
        self.label_14.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(650, 310, 171, 20))
        self.label_15.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(650, 420, 171, 20))
        self.label_16.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(650, 450, 171, 20))
        self.label_17.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(650, 560, 171, 20))
        self.label_18.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(650, 530, 171, 20))
        self.label_19.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(120, 560, 171, 20))
        self.label_20.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(120, 530, 171, 20))
        self.label_21.setStyleSheet("font: 9pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(340, 680, 191, 41))
        self.pushButton.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Chamber Size"))
        self.label_3.setText(_translate("Dialog", "Chamber Size"))
        self.label_4.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_5.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_6.setText(_translate("Dialog", "Chamber Size"))
        self.label_7.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_8.setText(_translate("Dialog", "Chamber Size"))
        self.label_9.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_10.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_11.setText(_translate("Dialog", "Chamber Size"))
        self.label_12.setText(_translate("Dialog", "Chamber Size"))
        self.label_13.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_14.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_15.setText(_translate("Dialog", "Chamber Size"))
        self.label_16.setText(_translate("Dialog", "Chamber Size"))
        self.label_17.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_18.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_19.setText(_translate("Dialog", "Chamber Size"))
        self.label_20.setText(_translate("Dialog", "Slack Adjuster"))
        self.label_21.setText(_translate("Dialog", "Chamber Size"))
        self.pushButton.setText(_translate("Dialog", "Save + Calculate"))

import wheelNum

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())